CREATE TABLE PCX.ListOfProducts (
    [Launch Date] NVARCHAR(MAX) NULL,
    [Brand] NVARCHAR(100) NULL,
    [Withdraw Date] NVARCHAR(MAX) NULL,
    [Withdraw Code] NVARCHAR(MAX) NULL,
    [MSP-LBG Product Code] NVARCHAR(MAX) NULL,
    [Channel Type] NVARCHAR(MAX) NULL,
    [Customer Type] NVARCHAR(MAX) NULL,

    [Term] DECIMAL(5,2) NULL,
    [Type] NVARCHAR(50) NULL,

    [BOE1+/-] DECIMAL(5,2) NULL,
    [Rate1] DECIMAL(5,2) NULL,
    [Until1] NVARCHAR(MAX) NULL,

    [BOE2+/-] DECIMAL(5,2) NULL,
    [Rate2] DECIMAL(5,2) NULL,
    [Until2] NVARCHAR(MAX) NULL,

    [BOE3+/-] DECIMAL(5,2) NULL,
    [Rate3] DECIMAL(5,2) NULL,
    [Until3] NVARCHAR(MAX) NULL,

    [BOE4+/-] DECIMAL(5,2) NULL,
    [Rate4] DECIMAL(5,2) NULL,
    [Until4] NVARCHAR(MAX) NULL,

    [BOE5+/-] DECIMAL(5,2) NULL,
    [Rate5] DECIMAL(5,2) NULL,
    [Until5] NVARCHAR(MAX) NULL,

    [BOE6+/-] DECIMAL(5,2) NULL,
    [Rate6] DECIMAL(5,2) NULL,
    [Until6] NVARCHAR(MAX) NULL,

    [BOE7+/-] DECIMAL(5,2) NULL,
    [Rate7] DECIMAL(5,2) NULL,
    [Until7] NVARCHAR(MAX) NULL,

    [BOE8+/-] DECIMAL(5,2) NULL,
    [Rate8] DECIMAL(5,2) NULL,
    [Until8] NVARCHAR(MAX) NULL,

    [Product Fee (£)] INT NULL,
    [Product Fee (%)] INT NULL,

    [Min Loan] INT NULL,
    [Max Loan] INT NULL,
    [Min LTV] INT NULL,
    [Max LTV] INT NULL,

    [Additional info] NVARCHAR(MAX) NULL,
    [Must Complete By] NVARCHAR(MAX) NULL,
    [Product Fee Acknum] NVARCHAR(50) NULL,
    [Repayment APR] DECIMAL(5,2) NULL,
    [Scheme Type] NVARCHAR(MAX) NULL,
    [Portable Product] NVARCHAR(50) NULL,
    [Panel Number] INT NULL,
    [Payee Number] NVARCHAR(50) NULL,
    [Interest Calculation] NVARCHAR(50) NULL,
    [Link to HVR / HHVR] NVARCHAR(50) NULL,
    [Refund of Val] NVARCHAR(50) NULL,
    [Val Refund Acknum] NVARCHAR(50) NULL,
    [Free Val] NVARCHAR(50) NULL,
    [Free Conveyancing] NVARCHAR(50) NULL,
    [DAF to be waived] NVARCHAR(50) NULL,
    [HLC Free] NVARCHAR(50) NULL,

    [Cashback (£)] INT NULL,
    [Cashback (%)] NVARCHAR(50) NULL,
    [Cashback Acknum] NVARCHAR(50) NULL,
    [Proc Fee Code] NVARCHAR(50) NULL,
    [Proc Fee Narrative] NVARCHAR(50) NULL,

    [Tied Insurance Free Format Text] NVARCHAR(MAX) NULL,
    [Tied Non Insurance Free Format Text] NVARCHAR(MAX) NULL,
    [Tied Incentivised Free Format Text] NVARCHAR(MAX) NULL,
    [Narrative] NVARCHAR(MAX) NULL,

    [Best Credit Score Applicable] NVARCHAR(50) NULL,
    [Worst Credit Score Applicable] NVARCHAR(50) NULL,
    [CarbonOffset (%)] NVARCHAR(50) NULL,
    [Calculator] NVARCHAR(50) NULL,
    [Extras] INT NULL,
    [BERR (Government Reporting)] NVARCHAR(50) NULL,

    [ERC Rate1] DECIMAL(5,2) NULL,
    [ERC Until1] NVARCHAR(MAX) NULL,
    [ERC Rate2] DECIMAL(5,2) NULL,
    [ERC Until2] NVARCHAR(MAX) NULL,
    [ERC Rate3] DECIMAL(5,2) NULL,
    [ERC Until3] NVARCHAR(MAX) NULL,
    [ERC Rate4] DECIMAL(5,2) NULL,
    [ERC Until4] NVARCHAR(MAX) NULL,
    [ERC Rate5] DECIMAL(5,2) NULL,
    [ERC Until5] NVARCHAR(MAX) NULL,
    [ERC Rate6] DECIMAL(5,2) NULL,
    [ERC Until6] NVARCHAR(MAX) NULL,
    [ERC Rate7] DECIMAL(5,2) NULL,
    [ERC Until7] NVARCHAR(MAX) NULL,
    [ERC Rate8] DECIMAL(5,2) NULL,
    [ERC Until8] NVARCHAR(MAX) NULL,

    [Cashback Minimum Amount] INT NULL,
    [Cashback Maximum Amount] INT NULL,
    [Cashback Type] NVARCHAR(50) NULL,
    [Repayment Fees] NVARCHAR(MAX) NULL,

    [Portable Tied Non Insurance Free Format Text] NVARCHAR(MAX) NULL,
    [Portable Tied Incentivised Free Format Text] NVARCHAR(MAX) NULL,

    [UFSS Interest Only Product Code (CGM)] NVARCHAR(50) NULL,
    [UFSS Repayment Product Code (CGM)] NVARCHAR(50) NULL,
    [UFSS Interest Only Product Code (MOR)] NVARCHAR(50) NULL,
    [UFSS Repayment Product Code (MOR)] NVARCHAR(50) NULL,
    [UFSS Interest Only Product Code (LBM)] NVARCHAR(50) NULL,
    [UFSS Repayment Product Code (LBM)] NVARCHAR(50) NULL,
    [UFSS Interest Only Product Code (BMG)] NVARCHAR(50) NULL,
    [UFSS Repayment Product Code (BMG)] NVARCHAR(50) NULL,

    [Account Type] NVARCHAR(50) NULL,
    [Current Product Cessation Type] NVARCHAR(50) NULL,
    [Risk Type] INT NULL,
    [Product String] NVARCHAR(MAX) NULL,
    [Withdrawn SOLAR code] NVARCHAR(50) NULL,
    [SOLAR CODE] NVARCHAR(50) NULL,
    [CHAPS Fee] INT NULL,
    [Channel Type / Category] NVARCHAR(MAX) NULL,
    [Core / Exclusive] NVARCHAR(50) NULL,
    [Offset Available] NVARCHAR(50) NULL,
    [CI] NVARCHAR(50) NULL,
    [IO] NVARCHAR(50) NULL,
    [ERC Term (Yrs)] INT NULL,
    [Individual LOP] NVARCHAR(MAX) NULL,
    [ERC Code] NVARCHAR(50) NULL,
    [Complete By] NVARCHAR(50) NULL,
    [MPET Valuation] NVARCHAR(50) NULL,
    [MPET Legal] NVARCHAR(50) NULL,
    [Core] NVARCHAR(50) NULL,
    [IRLID] NVARCHAR(50) NULL,
    [Interest Rate Code] NVARCHAR(50) NULL,
    [Mortgage Type] INT NULL
);
